import Head from "next/head";

type LayoutProps = {
  title?: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({
  title = "My Countdowns",
  description = "Generated by create-t3-app",
  children,
}: LayoutProps) {
  return (
    <div className="flex min-h-screen flex-col">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className="h-16 border-b bg-white">NAVBAR</nav>
      <main className="flex-1">{children}</main>
    </div>
  );
}

export default Layout;
