import Head from "next/head";
import Navbar from "./navbar";

type LayoutProps = {
  title?: string;
  description?: string;
  children: React.ReactNode;
};

function Layout({
  title = "My Countdowns",
  description = "Generated by create-t3-app",
  children,
}: LayoutProps) {
  return (
    <div className="flex min-h-screen flex-col">
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="container my-6 flex-1 lg:my-10">{children}</main>
    </div>
  );
}

export default Layout;
